import 'package:flutter/material.dart';
                                          import '../models/repo_model.dart';
                                          import 'repo_readme_page.dart';

                                          const kPrimaryColor = Color(0xFF3489FE);
                                          const kBackgroundColor = Color(0xFF262729);

                                          final List<RepoModel> repos = [
                                            // --- Aprendizaje y Recursos ---
                                            RepoModel(
                                              name: "freeCodeCamp",
                                              description: "Plataforma gratuita para aprender a programar.",
                                              scriptFile: "freecodecamp.sh",
                                              readmeAsset: "assets/readmes/freecodecamp.md",
                                              githubUrl: "https://github.com/freeCodeCamp/freeCodeCamp",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "Ebook Foundation Free Programming Books",
                                              description: "Libros gratuitos de programación en muchos lenguajes.",
                                              scriptFile: "free_programming_books.sh",
                                              readmeAsset: "assets/readmes/free_programming_books.md",
                                              githubUrl: "https://github.com/EbookFoundation/free-programming-books",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "The Algorithms - Python",
                                              description: "Implementaciones de algoritmos en Python.",
                                              scriptFile: "the_algorithms_python.sh",
                                              readmeAsset: "assets/readmes/the_algorithms_python.md",
                                              githubUrl: "https://github.com/TheAlgorithms/Python",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "JavaScript Algorithms",
                                              description: "Algoritmos y estructuras de datos en JavaScript.",
                                              scriptFile: "js_algorithms.sh",
                                              readmeAsset: "assets/readmes/js_algorithms.md",
                                              githubUrl: "https://github.com/trekhleb/javascript-algorithms",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "OSSU Computer Science",
                                              description: "Plan de estudios de informática abierto y gratuito.",
                                              scriptFile: "ossu_cs.sh",
                                              readmeAsset: "assets/readmes/ossu_cs.md",
                                              githubUrl: "https://github.com/ossu/computer-science",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "Project-Based Learning",
                                              description: "Aprende programación creando proyectos.",
                                              scriptFile: "project_based_learning.sh",
                                              readmeAsset: "assets/readmes/project_based_learning.md",
                                              githubUrl: "https://github.com/practical-tutorials/project-based-learning",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "You-Dont-Know-JS",
                                              description: "Serie de libros para entender JavaScript a fondo.",
                                              scriptFile: "you_dont_know_js.sh",
                                              readmeAsset: "assets/readmes/you_dont_know_js.md",
                                              githubUrl: "https://github.com/getify/You-Dont-Know-JS",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "Python-100-Days",
                                              description: "100 días de ejercicios prácticos de Python.",
                                              scriptFile: "python_100_days.sh",
                                              readmeAsset: "assets/readmes/python_100_days.md",
                                              githubUrl: "https://github.com/jackfrued/Python-100-Days",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "Learn Git Branching",
                                              description: "Juego interactivo para aprender Git.",
                                              scriptFile: "learn_git_branching.sh",
                                              readmeAsset: "assets/readmes/learn_git_branching.md",
                                              githubUrl: "https://github.com/pcottle/learnGitBranching",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "Awesome",
                                              description: "Listas curadas de recursos increíbles.",
                                              scriptFile: "awesome.sh",
                                              readmeAsset: "assets/readmes/awesome.md",
                                              githubUrl: "https://github.com/sindresorhus/awesome",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            // --- Herramientas y Utilidades ---
                                            RepoModel(
                                              name: "Oh My Zsh",
                                              description: "Framework para gestionar tu configuración de Zsh.",
                                              scriptFile: "ohmyzsh.sh",
                                              readmeAsset: "assets/readmes/ohmyzsh.md",
                                              githubUrl: "https://github.com/ohmyzsh/ohmyzsh",
                                              category: "Herramientas y Utilidades",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "Powerlevel10k",
                                              description: "Tema de Zsh rápido y personalizable.",
                                              scriptFile: "powerlevel10k.sh",
                                              readmeAsset: "assets/readmes/powerlevel10k.md",
                                              githubUrl: "https://github.com/romkatv/powerlevel10k",
                                              category: "Herramientas y Utilidades",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "fzf",
                                              description: "Fuzzy finder de línea de comandos.",
                                              scriptFile: "fzf.sh",
                                              readmeAsset: "assets/readmes/fzf.md",
                                              githubUrl: "https://github.com/junegunn/fzf",
                                              category: "Herramientas y Utilidades",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "exa",
                                              description: "Reemplazo moderno para 'ls'.",
                                              scriptFile: "exa.sh",
                                              readmeAsset: "assets/readmes/exa.md",
                                              githubUrl: "https://github.com/ogham/exa",
                                              category: "Herramientas y Utilidades",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "ripgrep",
                                              description: "Búsqueda recursiva ultrarrápida en archivos.",
                                              scriptFile: "ripgrep.sh",
                                              readmeAsset: "assets/readmes/ripgrep.md",
                                              githubUrl: "https://github.com/BurntSushi/ripgrep",
                                              category: "Herramientas y Utilidades",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "bat",
                                              description: "Cat mejorado con resaltado de sintaxis.",
                                              scriptFile: "bat.sh",
                                              readmeAsset: "assets/readmes/bat.md",
                                              githubUrl: "https://github.com/sharkdp/bat",
                                              category: "Herramientas y Utilidades",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "fd",
                                              description: "Encuentra archivos/directorios rápidamente.",
                                              scriptFile: "fd.sh",
                                              readmeAsset: "assets/readmes/fd.md",
                                              githubUrl: "https://github.com/sharkdp/fd",
                                              category: "Herramientas y Utilidades",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "hexyl",
                                              description: "Visor hexadecimal de línea de comandos.",
                                              scriptFile: "hexyl.sh",
                                              readmeAsset: "assets/readmes/hexyl.md",
                                              githubUrl: "https://github.com/sharkdp/hexyl",
                                              category: "Herramientas y Utilidades",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "neofetch",
                                              description: "Muestra información del sistema en la terminal.",
                                              scriptFile: "neofetch.sh",
                                              readmeAsset: "assets/readmes/neofetch.md",
                                              githubUrl: "https://github.com/dylanaraps/neofetch",
                                              category: "Herramientas y Utilidades",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "Termux API",
                                              description: "Acceso a funciones avanzadas de Android desde Termux.",
                                              scriptFile: "termux-api.sh",
                                              readmeAsset: "assets/readmes/termux-api.md",
                                              githubUrl: "https://github.com/termux/termux-api",
                                              category: "Herramientas y Utilidades",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            // --- Seguridad y Pentesting ---
                                            RepoModel(
                                              name: "Havoc Framework",
                                              description: "Framework de post-explotación y C2.",
                                              scriptFile: "havoc-framework.sh",
                                              readmeAsset: "assets/readmes/havoc-framework.md",
                                              githubUrl: "https://github.com/HavocFramework/Havoc",
                                              category: "Seguridad y Pentesting",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "hcxdumptool",
                                              description: "Herramienta para capturar handshakes de WiFi.",
                                              scriptFile: "hcxdumptool.sh",
                                              readmeAsset: "assets/readmes/hcxdumptool.md",
                                              githubUrl: "https://github.com/ZerBea/hcxdumptool",
                                              category: "Seguridad y Pentesting",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "sublist3r",
                                              description: "Enumeración de subdominios rápida.",
                                              scriptFile: "sublist3r.sh",
                                              readmeAsset: "assets/readmes/sublist3r.md",
                                              githubUrl: "https://github.com/aboul3la/Sublist3r",
                                              category: "Seguridad y Pentesting",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "amass",
                                              description: "Enumeración avanzada de activos y subdominios.",
                                              scriptFile: "amass.sh",
                                              readmeAsset: "assets/readmes/amass.md",
                                              githubUrl: "https://github.com/owasp-amass/amass",
                                              category: "Seguridad y Pentesting",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "masscan",
                                              description: "Escáner de puertos TCP ultrarrápido.",
                                              scriptFile: "masscan.sh",
                                              readmeAsset: "assets/readmes/masscan.md",
                                              githubUrl: "https://github.com/robertdavidgraham/masscan",
                                              category: "Seguridad y Pentesting",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "pwncat",
                                              description: "Herramienta de post-explotación y shells reversas.",
                                              scriptFile: "pwncat.sh",
                                              readmeAsset: "assets/readmes/pwncat.md",
                                              githubUrl: "https://github.com/calebstewart/pwncat",
                                              category: "Seguridad y Pentesting",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "proot-distro",
                                              description: "Instala distribuciones GNU/Linux en Termux.",
                                              scriptFile: "proot-distro.sh",
                                              readmeAsset: "assets/readmes/proot-distro.md",
                                              githubUrl: "https://github.com/termux/proot-distro",
                                              category: "Seguridad y Pentesting",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "mitmf",
                                              description: "Framework para ataques Man-In-The-Middle.",
                                              scriptFile: "mitmf.sh",
                                              readmeAsset: "assets/readmes/mitmf.md",
                                              githubUrl: "https://github.com/byt3bl33d3r/MITMf",
                                              category: "Seguridad y Pentesting",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "routersploit",
                                              description: "Framework de explotación para routers.",
                                              scriptFile: "routersploit.sh",
                                              readmeAsset: "assets/readmes/routersploit.md",
                                              githubUrl: "https://github.com/threat9/routersploit",
                                              category: "Seguridad y Pentesting",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "scapy",
                                              description: "Manipulación de paquetes y análisis de red.",
                                              scriptFile: "scapy.sh",
                                              readmeAsset: "assets/readmes/scapy.md",
                                              githubUrl: "https://github.com/secdev/scapy",
                                              category: "Seguridad y Pentesting",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            // --- Terminal y Personalización ---
                                            RepoModel(
                                              name: "Termux App",
                                              description: "Terminal de Android con entorno Linux.",
                                              scriptFile: "termux-app.sh",
                                              readmeAsset: "assets/readmes/termux-app.md",
                                              githubUrl: "https://github.com/termux/termux-app",
                                              category: "Terminal y Personalización",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "Termux Styling",
                                              description: "Personaliza la apariencia de Termux.",
                                              scriptFile: "termux-styling.sh",
                                              readmeAsset: "assets/readmes/termux-styling.md",
                                              githubUrl: "https://github.com/termux/termux-styling",
                                              category: "Terminal y Personalización",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "antigen",
                                              description: "Gestor de plugins para Zsh.",
                                              scriptFile: "antigen.sh",
                                              readmeAsset: "assets/readmes/antigen.md",
                                              githubUrl: "https://github.com/zsh-users/antigen",
                                              category: "Terminal y Personalización",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "zsh-syntax-highlighting",
                                              description: "Resaltado de sintaxis para Zsh.",
                                              scriptFile: "zsh-syntax-highlighting.sh",
                                              readmeAsset: "assets/readmes/zsh-syntax-highlighting.md",
                                              githubUrl: "https://github.com/zsh-users/zsh-syntax-highlighting",
                                              category: "Terminal y Personalización",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "zsh-autosuggestions",
                                              description: "Sugerencias automáticas en Zsh.",
                                              scriptFile: "zsh-autosuggestions.sh",
                                              readmeAsset: "assets/readmes/zsh-autosuggestions.md",
                                              githubUrl: "https://github.com/zsh-users/zsh-autosuggestions",
                                              category: "Terminal y Personalización",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            // --- Chat, Mensajería y Red ---
                                            RepoModel(
                                              name: "weechat",
                                              description: "Cliente de chat IRC extensible.",
                                              scriptFile: "weechat.sh",
                                              readmeAsset: "assets/readmes/weechat.md",
                                              githubUrl: "https://github.com/weechat/weechat",
                                              category: "Chat, Mensajería y Red",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "bettercap",
                                              description: "Herramienta avanzada de red y pentesting.",
                                              scriptFile: "bettercap.sh",
                                              readmeAsset: "assets/readmes/bettercap.md",
                                              githubUrl: "https://github.com/bettercap/bettercap",
                                              category: "Chat, Mensajería y Red",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "drozer",
                                              description: "Framework de seguridad para Android.",
                                              scriptFile: "drozer.sh",
                                              readmeAsset: "assets/readmes/drozer.md",
                                              githubUrl: "https://github.com/FSecureLABS/drozer",
                                              category: "Chat, Mensajería y Red",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "feroxbuster",
                                              description: "Fuerza bruta de directorios y archivos web.",
                                              scriptFile: "feroxbuster.sh",
                                              readmeAsset: "assets/readmes/feroxbuster.md",
                                              githubUrl: "https://github.com/epi052/feroxbuster",
                                              category: "Chat, Mensajería y Red",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            // --- Repos extra para llegar a 50 ---
                                            RepoModel(
                                              name: "fastapi",
                                              description: "Framework web moderno y rápido para Python.",
                                              scriptFile: "fastapi.sh",
                                              readmeAsset: "assets/readmes/fastapi.md",
                                              githubUrl: "https://github.com/tiangolo/fastapi",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "django",
                                              description: "Framework web de alto nivel para Python.",
                                              scriptFile: "django.sh",
                                              readmeAsset: "assets/readmes/django.md",
                                              githubUrl: "https://github.com/django/django",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "flask",
                                              description: "Microframework web para Python.",
                                              scriptFile: "flask.sh",
                                              readmeAsset: "assets/readmes/flask.md",
                                              githubUrl: "https://github.com/pallets/flask",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "react",
                                              description: "Librería para construir interfaces de usuario.",
                                              scriptFile: "react.sh",
                                              readmeAsset: "assets/readmes/react.md",
                                              githubUrl: "https://github.com/facebook/react",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "vue",
                                              description: "Framework progresivo para construir interfaces.",
                                              scriptFile: "vue.sh",
                                              readmeAsset: "assets/readmes/vue.md",
                                              githubUrl: "https://github.com/vuejs/vue",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "angular",
                                              description: "Framework para aplicaciones web robustas.",
                                              scriptFile: "angular.sh",
                                              readmeAsset: "assets/readmes/angular.md",
                                              githubUrl: "https://github.com/angular/angular",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "flutter",
                                              description: "Framework para apps móviles multiplataforma.",
                                              scriptFile: "flutter.sh",
                                              readmeAsset: "assets/readmes/flutter.md",
                                              githubUrl: "https://github.com/flutter/flutter",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "kotlin",
                                              description: "Lenguaje moderno para JVM y Android.",
                                              scriptFile: "kotlin.sh",
                                              readmeAsset: "assets/readmes/kotlin.md",
                                              githubUrl: "https://github.com/JetBrains/kotlin",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "spring-boot",
                                              description: "Framework para microservicios en Java.",
                                              scriptFile: "spring_boot.sh",
                                              readmeAsset: "assets/readmes/spring_boot.md",
                                              githubUrl: "https://github.com/spring-projects/spring-boot",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "node",
                                              description: "Entorno de ejecución para JavaScript.",
                                              scriptFile: "node.sh",
                                              readmeAsset: "assets/readmes/node.md",
                                              githubUrl: "https://github.com/nodejs/node",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "express",
                                              description: "Framework web minimalista para Node.js.",
                                              scriptFile: "express.sh",
                                              readmeAsset: "assets/readmes/express.md",
                                              githubUrl: "https://github.com/expressjs/express",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "nestjs",
                                              description: "Framework para aplicaciones Node.js escalables.",
                                              scriptFile: "nestjs.sh",
                                              readmeAsset: "assets/readmes/nestjs.md",
                                              githubUrl: "https://github.com/nestjs/nest",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "laravel",
                                              description: "Framework web para PHP elegante y expresivo.",
                                              scriptFile: "laravel.sh",
                                              readmeAsset: "assets/readmes/laravel.md",
                                              githubUrl: "https://github.com/laravel/laravel",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "symfony",
                                              description: "Framework PHP para aplicaciones web.",
                                              scriptFile: "symfony.sh",
                                              readmeAsset: "assets/readmes/symfony.md",
                                              githubUrl: "https://github.com/symfony/symfony",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "rails",
                                              description: "Framework web para Ruby.",
                                              scriptFile: "rails.sh",
                                              readmeAsset: "assets/readmes/rails.md",
                                              githubUrl: "https://github.com/rails/rails",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "go",
                                              description: "Lenguaje de programación eficiente y simple.",
                                              scriptFile: "go.sh",
                                              readmeAsset: "assets/readmes/go.md",
                                              githubUrl: "https://github.com/golang/go",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "rust",
                                              description: "Lenguaje de sistemas rápido y seguro.",
                                              scriptFile: "rust.sh",
                                              readmeAsset: "assets/readmes/rust.md",
                                              githubUrl: "https://github.com/rust-lang/rust",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "cppreference",
                                              description: "Referencia colaborativa para C++.",
                                              scriptFile: "cppreference.sh",
                                              readmeAsset: "assets/readmes/cppreference.md",
                                              githubUrl: "https://github.com/CppReference/CppReference",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "awesome-python",
                                              description: "Lista curada de recursos de Python.",
                                              scriptFile: "awesome_python.sh",
                                              readmeAsset: "assets/readmes/awesome_python.md",
                                              githubUrl: "https://github.com/vinta/awesome-python",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                            RepoModel(
                                              name: "public-apis",
                                              description: "APIs públicas gratuitas para desarrollo.",
                                              scriptFile: "public_apis.sh",
                                              readmeAsset: "assets/readmes/public_apis.md",
                                              githubUrl: "https://github.com/public-apis/public-apis",
                                              category: "Aprendizaje y Recursos",
                                              iconAsset: "assets/icons/iconrepo.png",
                                            ),
                                          ];

                                          class HomePage extends StatelessWidget {
                                            const HomePage({super.key});

                                            Map<String, List<RepoModel>> get reposPorCategoria {
                                              final map = <String, List<RepoModel>>{};
                                              for (final repo in repos) {
                                                map.putIfAbsent(repo.category, () => []).add(repo);
                                              }
                                              return map;
                                            }

                                            @override
                                            Widget build(BuildContext context) {
                                              final categorias = reposPorCategoria.keys.toList();
                                              return Scaffold(
                                                backgroundColor: kBackgroundColor,
                                                body: ListView.builder(
                                                  padding: const EdgeInsets.all(16),
                                                  itemCount: categorias.length,
                                                  itemBuilder: (context, catIndex) {
                                                    final categoria = categorias[catIndex];
                                                    final lista = reposPorCategoria[categoria]!;
                                                    return Column(
                                                      crossAxisAlignment: CrossAxisAlignment.start,
                                                      children: [
                                                        Padding(
                                                          padding: const EdgeInsets.symmetric(vertical: 10),
                                                          child: Text(
                                                            categoria,
                                                            style: const TextStyle(
                                                              color: kPrimaryColor,
                                                              fontSize: 22,
                                                              fontWeight: FontWeight.bold,
                                                              letterSpacing: 1.1,
                                                            ),
                                                          ),
                                                        ),
                                                        ...lista.asMap().entries.map((entry) {
                                                          final repo = entry.value;
                                                          return Container(
                                                            margin: const EdgeInsets.symmetric(vertical: 8),
                                                            child: Card(
                                                              color: kBackgroundColor,
                                                              elevation: 5,
                                                              shadowColor: kPrimaryColor.withOpacity(0.18),
                                                              shape: RoundedRectangleBorder(
                                                                borderRadius: BorderRadius.circular(16),
                                                                side: const BorderSide(color: kPrimaryColor, width: 1),
                                                              ),
                                                              child: ListTile(
                                                                contentPadding: const EdgeInsets.symmetric(
                                                                  horizontal: 20,
                                                                  vertical: 18,
                                                                ),
                                                                leading: CircleAvatar(
                                                                  backgroundColor: Colors.transparent,
                                                                  child: Image.asset(
                                                                    repo.iconAsset,
                                                                    width: 36,
                                                                    height: 36,
                                                                    fit: BoxFit.contain,
                                                                  ),
                                                                ),
                                                                title: Text(
                                                                  repo.name,
                                                                  style: const TextStyle(
                                                                    color: Colors.white,
                                                                    fontSize: 18,
                                                                    fontWeight: FontWeight.w600,
                                                                  ),
                                                                ),
                                                                subtitle: Padding(
                                                                  padding: const EdgeInsets.only(top: 6),
                                                                  child: Text(
                                                                    repo.description,
                                                                    style: const TextStyle(
                                                                      color: Colors.white70,
                                                                      fontSize: 15,
                                                                    ),
                                                                  ),
                                                                ),
                                                                trailing: Tooltip(
                                                                  message: 'Ver detalles',
                                                                  child: ElevatedButton.icon(
                                                                    icon: const Icon(Icons.arrow_forward, size: 20),
                                                                    label: const Text("Ver"),
                                                                    style: ElevatedButton.styleFrom(
                                                                      backgroundColor: kPrimaryColor,
                                                                      foregroundColor: Colors.white,
                                                                      shape: RoundedRectangleBorder(
                                                                        borderRadius: BorderRadius.circular(8),
                                                                      ),
                                                                      padding: const EdgeInsets.symmetric(
                                                                        horizontal: 16,
                                                                        vertical: 10,
                                                                      ),
                                                                      textStyle: const TextStyle(
                                                                        fontWeight: FontWeight.bold,
                                                                        fontSize: 15,
                                                                      ),
                                                                      elevation: 4,
                                                                    ),
                                                                    onPressed: () {
                                                                      Navigator.of(context).push(
                                                                        MaterialPageRoute(
                                                                          builder: (_) => RepoReadmePage(
                                                                            repoName: repo.name,
                                                                            scriptFile: repo.scriptFile,
                                                                            readmeAsset: repo.readmeAsset,
                                                                            githubUrl: repo.githubUrl,
                                                                          ),
                                                                        ),
                                                                      );
                                                                    },
                                                                  ),
                                                                ),
                                                              ),
                                                            ),
                                                          );
                                                        }),
                                                        const SizedBox(height: 18),
                                                      ],
                                                    );
                                                  },
                                                ),
                                              );
                                            }
                                          }