name: rk13
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  clipboard: ^0.1.3
  android_intent_plus: ^5.3.0
  cupertino_icons: ^1.0.8
  permission_handler: ^11.0.0
  another_flushbar: ^1.10.29
  fluttertoast: ^8.2.4
  flutter_markdown: ^0.6.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/scripts/aircrack-ng.sh
    - assets/scripts/beef.sh
    - assets/scripts/burpsuite.sh
    - assets/scripts/dirb.sh
    - assets/scripts/dnsenum.sh
    - assets/scripts/ettercap.sh
    - assets/scripts/fierce.sh
    - assets/scripts/ghostphisher.sh
    - assets/scripts/hashcat.sh
    - assets/scripts/hydra.sh
    - assets/scripts/johntheripper.sh
    - assets/scripts/maltego.sh
    - assets/scripts/metasploit.sh
    - assets/scripts/netcat.sh
    - assets/scripts/nikto.sh
    - assets/scripts/nmap.sh
    - assets/scripts/recon-ng.sh
    - assets/scripts/redhawk.sh
    - assets/scripts/setoolkit.sh
    - assets/scripts/slowloris.sh
    - assets/scripts/socialfish.sh
    - assets/scripts/sqlmap.sh
    - assets/scripts/tcpdump.sh
    - assets/scripts/theharvester.sh
    - assets/scripts/trity.sh
    - assets/scripts/wireshark.sh
    - assets/scripts/wpscan.sh
    - assets/scripts/xerosploit.sh
    - assets/scripts/yersinia.sh
    - assets/scripts/zphisher.sh
    - assets/readmes/aircrack-ng.md
    - assets/readmes/beef.md
    - assets/readmes/burpsuite.md
    - assets/readmes/dirb.md
    - assets/readmes/dnsenum.md
    - assets/readmes/ettercap.md
    - assets/readmes/fierce.md
    - assets/readmes/ghostphisher.md
    - assets/readmes/hashcat.md
    - assets/readmes/hydra.md
    - assets/readmes/johntheripper.md
    - assets/readmes/maltego.md
    - assets/readmes/metasploit.md
    - assets/readmes/netcat.md
    - assets/readmes/nikto.md
    - assets/readmes/nmap.md
    - assets/readmes/recon-ng.md
    - assets/readmes/redhawk.md
    - assets/readmes/setoolkit.md
    - assets/readmes/slowloris.md
    - assets/readmes/socialfish.md
    - assets/readmes/sqlmap.md
    - assets/readmes/tcpdump.md
    - assets/readmes/theharvester.md
    - assets/readmes/trity.md
    - assets/readmes/wireshark.md
    - assets/readmes/wpscan.md
    - assets/readmes/xerosploit.md
    - assets/readmes/yersinia.md
    - assets/readmes/zphisher.md

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
