name: rk13
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  clipboard: ^0.1.3
  android_intent_plus: ^5.3.0
  cupertino_icons: ^1.0.8
  permission_handler: ^11.0.0
  another_flushbar: ^1.10.29
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_markdown: ^0.6.17

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - assets/scripts/nmap.sh
      - assets/scripts/hydra.sh
      - assets/scripts/metasploit.sh
      - assets/scripts/sqlmap.sh
      - assets/scripts/aircrack-ng.sh
      - assets/scripts/wireshark.sh
      - assets/scripts/john.sh
      - assets/scripts/burpsuite.sh
      - assets/scripts/ettercap.sh
      - assets/scripts/netcat.sh
      - assets/scripts/recon-ng.sh
      - assets/scripts/nikto.sh
      - assets/scripts/wpscan.sh
      - assets/scripts/beef.sh
      - assets/scripts/msfpc.sh
      - assets/scripts/routersploit.sh
      - assets/scripts/apktool.sh
      - assets/scripts/hashcat.sh
      - assets/scripts/slowloris.sh
      - assets/scripts/setoolkit.sh
      - assets/scripts/maltego.sh
      - assets/scripts/dnsenum.sh
      - assets/scripts/theharvester.sh
      - assets/scripts/enum4linux.sh
      - assets/scripts/dirb.sh
      - assets/scripts/fierce.sh
      - assets/scripts/sslscan.sh
      - assets/scripts/xsser.sh
      - assets/scripts/skipfish.sh
      - assets/scripts/zmap.sh
      - assets/readmes/nmap.md
      - assets/readmes/hydra.md
      - assets/readmes/metasploit.md
      - assets/readmes/sqlmap.md
      - assets/readmes/aircrack-ng.md
      - assets/readmes/wireshark.md
      - assets/readmes/john.md
      - assets/readmes/burpsuite.md
      - assets/readmes/ettercap.md
      - assets/readmes/netcat.md
      - assets/readmes/recon-ng.md
      - assets/readmes/nikto.md
      - assets/readmes/wpscan.md
      - assets/readmes/beef.md
      - assets/readmes/msfpc.md
      - assets/readmes/routersploit.md
      - assets/readmes/apktool.md
      - assets/readmes/hashcat.md
      - assets/readmes/slowloris.md
      - assets/readmes/setoolkit.md
      - assets/readmes/maltego.md
      - assets/readmes/dnsenum.md
      - assets/readmes/theharvester.md
      - assets/readmes/enum4linux.md
      - assets/readmes/dirb.md
      - assets/readmes/fierce.md
      - assets/readmes/sslscan.md
      - assets/readmes/xsser.md
      - assets/readmes/skipfish.md
      - assets/readmes/zmap.md

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
